version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always

  postgres:
    image: postgres:13.5-alpine
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "54320:5432"

volumes:
  redis_data:
    driver: local
